apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - deployment.yaml
  - configmap.yaml

generators:
  - secrets-generator.yaml

commonLabels:
  app.kubernetes.io/name: cloudflared
  app.kubernetes.io/component: tunnel

