apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-rollouts-demo-fe
  namespace: argo-rollouts-demo
  annotations:
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/compute-full-forwarded-for: "true"
    external-dns.alpha.kubernetes.io/hostname: argo-rollouts-demo.jshipster.io
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: argo-rollouts-demo.jshipster.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-rollouts-demo-fe-service
            port:
              number: 80
