apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blutag-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - app.blutag.jshipster.io
    secretName: blutag-app-tls
  rules:
  - host: app.blutag.jshipster.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blutag-app
            port:
              number: 80
