apiVersion: v1
kind: Service
metadata:
  name: gen-rag-qdrant
  labels:
    app: gen-rag-qdrant
spec:
  ports:
  - port: 6333
    targetPort: 6333
    name: http
  - port: 6334
    targetPort: 6334
    name: grpc
  selector:
    app: gen-rag-qdrant
  clusterIP: None
