apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blutag-website
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - blutag.jshipster.io
    - blutag.argmaxml.com
    secretName: blutag-website-tls
  rules:
  - host: blutag.jshipster.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blutag-website
            port:
              number: 80
  - host: blutag.argmaxml.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blutag-website
            port:
              number: 80

