apiVersion: v1
kind: Service
metadata:
  name: jshipster-bastion
  labels:
    app: jshipster-bastion
  annotations:
    external-dns.alpha.kubernetes.io/hostname: debug.jshipster.io
spec:
  type: LoadBalancer
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP
    name: ssh
  selector:
    app: jshipster-bastion
