apiVersion: ENC[AES256_GCM,data:j4A=,iv:58kzEKIt2OaHkSP1E2nK5+Nb5V87tXi13WqRu4UPOfQ=,tag:WqHcy2dcoG0nVLD2NJgg6Q==,type:str]
kind: ENC[AES256_GCM,data:4WL1w88Q,iv:xW5NZPT8GG7a2G5BwJnovL9B1joW7ylOFlZtdQpY1RQ=,tag:sk0U4o+oC3DlnVabM1GAYQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rO5I6JNE6apMhSXceA==,iv:Di6ZMUEwe3OqEiBdX6q9BguZzFebx4KDgJuCgtlbfhk=,tag:H0jkLK/xhdYkD2Y46XpeYQ==,type:str]
    namespace: ENC[AES256_GCM,data:w3tZrnasjw==,iv:g1CEdmkjB6ypgYfoFkgW0kmZKuw/pRzLWMTXbAvNg+U=,tag:PNaFpnGMtWctqmFeT6y6UQ==,type:str]
type: ENC[AES256_GCM,data:2zsjCm6T,iv:E4sjdr8tdB+byY72lX5Blr5ZURNPsX4xLPkvFPfgR3w=,tag:D/y2NF4PywugCnu6odB/xA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:tKGCUpYOlqM=,iv:ATEzX/sFNxJ2KYxPrE7jiwnVWH81ZSK3Ph8e6WmPhMM=,tag:RQ/dfNg4jZKCdWILb8mJ4g==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMlhGMkJPcnVpVXdJOWJV
            VmxlNFhEbHlpOGw2aGZQdjAwQ3k2Zlhpb2dFCmFhcUxiaUMveEUrZXIvSHAwaEJB
            TGR6Zkc1VktMU1lOMUdwY1JJckFpb1UKLS0tIFYxdGMrTlgyMjFXNllpcTZ1S2pi
            UGIyeU4xOWVWRERoLzNIdW5EVWFCQmMKYkdyaPJcLZqudKk14Ioe2h3Xv6upjxlc
            WG72zWMUMaIjJnWYN4Q+1IoGttO5lqo0TSpHwapadgPIiDi0fUdnzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T14:18:31Z"
    mac: ENC[AES256_GCM,data:wN298CmJAg0htYqEzZYeh6NdiTXNCG28G4SgdZ3jqODnSIbN6ACj5T1dGrfFROTKGbxhBvLcKXtK68gRD2ySqhwDalk3IPWC2vUDtaXgF+kyRxGzIad1ucCeR/q/fTLosQ4KyLyuh454TGvQazY0uce9YSeIUJZoudxmT/KhQzE=,iv:bK2HQSJuyp8ceO8+l2AdP5HsHVudHjPWv7x5qgXbIvY=,tag:+CCUdlKJ6SIDaJ1YsIUVpA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
