apiVersion: v1
kind: ConfigMap
metadata:
  name: johnson-config
  labels:
    app: johnson
data:
  JOHNSON_ALLOWED_ORIGINS: "https://johnson.jshipster.io"
  WHATSAPP_TWILIO_FROM_NUMBER: "whatsapp:+972545918782"
  WHATSAPP_DEV_OVERRIDE_RECIPIENT: "+972545918782"
  JOHNSON_JWT_EXPIRATION_SECONDS: "2592000"

