apiVersion: apps/v1
kind: Deployment
metadata:
  name: johnson
  labels:
    app: johnson
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: johnson
  template:
    metadata:
      labels:
        app: johnson
    spec:
      initContainers:
      - name: johnson-migrations
        image: prodacr1234.azurecr.io/johnson-db-migrations:main-73901ff
        env:
        - name: JOHNSON_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: johnson-secrets
              key: JOHNSON_DATABASE_URL
      containers:
      - name: johnson
        image: prodacr1234.azurecr.io/johnson:main-73901ff
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        envFrom:
        - configMapRef:
            name: johnson-config
        - secretRef:
            name: johnson-secrets
        resources:
          requests:
            memory: "96Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 3
          failureThreshold: 2

