apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: johnson
  annotations:
    external-dns.alpha.kubernetes.io/hostname: johnson.jshipster.io
spec:
  ingressClassName: nginx
  rules:
  - host: johnson.jshipster.io
    http:
      paths:
      # Serve all routes through the unified app (API and frontend SPA)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: johnson
            port:
              number: 8000

