apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dirtbike-specialist
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: dirtbike.jshipster.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dirtbike-specialist
                port:
                  number: 80
  tls:
    - hosts:
        - dirtbike.jshipster.io
      secretName: dirtbike-tls
