apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjob.yaml
  - ids-analytics-cronjob.yaml
  - blutag-findmy-status-cronjob.yaml
  - serviceaccount.yaml
  # GCP Billing
  - gcp-billing-cronjob.yaml
  - gcp-serviceaccount.yaml

generators:
  - secrets-generator.yaml
  - gcp-secrets-generator.yaml
