apiVersion: v1
kind: Service
metadata:
  name: ids-qdrant
  labels:
    app: ids-qdrant
spec:
  type: ClusterIP
  ports:
  - port: 6333
    targetPort: 6333
    protocol: TCP
    name: http
  - port: 6334
    targetPort: 6334
    protocol: TCP
    name: grpc
  selector:
    app: ids-qdrant
