apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml

generators:
  - secrets-generator.yaml
