apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ids

resources:
  - pvc.yaml
  - serviceaccount.yaml
  - job.yaml
  - cleanup-serviceaccount.yaml
  - cleanup-cronjob.yaml

generators:
  - secrets-generator.yaml

